/* This file is generated by scripts/generate-image-manifest.mjs. */

export type QuizAnswer = "ai" | "human";

export type QuizImage = {
  id: string;
  src: string;
  answer: QuizAnswer;
  fileName: string;
};

export const quizImages: QuizImage[] = [
  {
    "id": "ai-1-MDEtZWxldmF0b3It",
    "src": "/ai/01-elevator-ootd%20(1).png",
    "answer": "ai",
    "fileName": "01-elevator-ootd (1).png"
  },
  {
    "id": "ai-2-MDItYmVkcm9vbS1t",
    "src": "/ai/02-bedroom-mirror.png",
    "answer": "ai",
    "fileName": "02-bedroom-mirror.png"
  },
  {
    "id": "ai-3-MDQtbGlmZXN0eWxl",
    "src": "/ai/04-lifestyle-seoul-street.png",
    "answer": "ai",
    "fileName": "04-lifestyle-seoul-street.png"
  },
  {
    "id": "ai-4-MDUtY2FyLWNsb3Nl",
    "src": "/ai/05-car-closeup.jpeg",
    "answer": "ai",
    "fileName": "05-car-closeup.jpeg"
  },
  {
    "id": "ai-5-MDUtc3Vid2F5LWNh",
    "src": "/ai/05-subway-candid.png",
    "answer": "ai",
    "fileName": "05-subway-candid.png"
  },
  {
    "id": "ai-6-Q2hhdEdQVCBJbWFn",
    "src": "/ai/ChatGPT%20Image%207%20%D0%BC%D0%B0%D1%8F%202026%20%D0%B3.%2C%2015_04_31%C2%A0%E2%80%94%20%D0%BA%D0%BE%D0%BF%D0%B8%D1%8F%20(1).png",
    "answer": "ai",
    "fileName": "ChatGPT Image 7 мая 2026 г., 15_04_31 — копия (1).png"
  },
  {
    "id": "ai-7-ZmluYWwtMDEgKDQp",
    "src": "/ai/final-01%20(4).png",
    "answer": "ai",
    "fileName": "final-01 (4).png"
  },
  {
    "id": "ai-8-ZmluYWwtMDEgKDYp",
    "src": "/ai/final-01%20(6).png",
    "answer": "ai",
    "fileName": "final-01 (6).png"
  },
  {
    "id": "ai-9-ZmluYWwtMDEgKDcp",
    "src": "/ai/final-01%20(7).png",
    "answer": "ai",
    "fileName": "final-01 (7).png"
  },
  {
    "id": "ai-10-ZmluYWwtMDEgKDgp",
    "src": "/ai/final-01%20(8).png",
    "answer": "ai",
    "fileName": "final-01 (8).png"
  },
  {
    "id": "ai-11-ZmluYWwtMDIgKDEw",
    "src": "/ai/final-02%20(10).png",
    "answer": "ai",
    "fileName": "final-02 (10).png"
  },
  {
    "id": "ai-12-ZmluYWwtMDIgKDEx",
    "src": "/ai/final-02%20(11).png",
    "answer": "ai",
    "fileName": "final-02 (11).png"
  },
  {
    "id": "ai-13-ZmluYWwtMDMgKDYp",
    "src": "/ai/final-03%20(6).png",
    "answer": "ai",
    "fileName": "final-03 (6).png"
  },
  {
    "id": "ai-14-ZmluYWwtMDUgKDEx",
    "src": "/ai/final-05%20(11).png",
    "answer": "ai",
    "fileName": "final-05 (11).png"
  },
  {
    "id": "ai-15-ZmluYWwtMDUgKDEy",
    "src": "/ai/final-05%20(12).png",
    "answer": "ai",
    "fileName": "final-05 (12).png"
  },
  {
    "id": "ai-16-ZmluYWwtMDYtZmxv",
    "src": "/ai/final-06-floor-brow.jpg",
    "answer": "ai",
    "fileName": "final-06-floor-brow.jpg"
  },
  {
    "id": "ai-17-aGZfMjAyNjA1MDdf",
    "src": "/ai/hf_20260507_053535_40f59618-b71c-4118-ae1c-a3d77e2919dd.png",
    "answer": "ai",
    "fileName": "hf_20260507_053535_40f59618-b71c-4118-ae1c-a3d77e2919dd.png"
  },
  {
    "id": "ai-18-c2hvdC0wMV9ncHQt",
    "src": "/ai/shot-01_gpt-image.png",
    "answer": "ai",
    "fileName": "shot-01_gpt-image.png"
  },
  {
    "id": "ai-19-c2hvdC0wMWIgKDEp",
    "src": "/ai/shot-01b%20(1).jpg",
    "answer": "ai",
    "fileName": "shot-01b (1).jpg"
  },
  {
    "id": "ai-20-c2hvdC0wMWIgKDIp",
    "src": "/ai/shot-01b%20(2).png",
    "answer": "ai",
    "fileName": "shot-01b (2).png"
  },
  {
    "id": "ai-21-c2hvdC0wMWJfbmFu",
    "src": "/ai/shot-01b_nano-pro%20(1).png",
    "answer": "ai",
    "fileName": "shot-01b_nano-pro (1).png"
  },
  {
    "id": "ai-22-c2hvdC0wMiAoMiku",
    "src": "/ai/shot-02%20(2).png",
    "answer": "ai",
    "fileName": "shot-02 (2).png"
  },
  {
    "id": "ai-23-c2hvdC0wMmFfbmFu",
    "src": "/ai/shot-02a_nano-pro%20(1).png",
    "answer": "ai",
    "fileName": "shot-02a_nano-pro (1).png"
  },
  {
    "id": "ai-24-c2hvdC0wMmIgKDEp",
    "src": "/ai/shot-02b%20(1).png",
    "answer": "ai",
    "fileName": "shot-02b (1).png"
  },
  {
    "id": "ai-25-c2hvdC0wMmIgKDIp",
    "src": "/ai/shot-02b%20(2).png",
    "answer": "ai",
    "fileName": "shot-02b (2).png"
  },
  {
    "id": "ai-26-c2hvdC0wMmJfbmFu",
    "src": "/ai/shot-02b_nano-pro.png",
    "answer": "ai",
    "fileName": "shot-02b_nano-pro.png"
  },
  {
    "id": "ai-27-c2hvdC0wMmJfbmFu",
    "src": "/ai/shot-02b_nano.jpg",
    "answer": "ai",
    "fileName": "shot-02b_nano.jpg"
  },
  {
    "id": "ai-28-c2hvdC0wM2FfbmFu",
    "src": "/ai/shot-03a_nano-pro%20(3).png",
    "answer": "ai",
    "fileName": "shot-03a_nano-pro (3).png"
  },
  {
    "id": "ai-29-c2hvdC0wM2FfbmFu",
    "src": "/ai/shot-03a_nano-pro%20(4).png",
    "answer": "ai",
    "fileName": "shot-03a_nano-pro (4).png"
  },
  {
    "id": "ai-30-c2hvdC0wM2FfbmFu",
    "src": "/ai/shot-03a_nano-pro%20(5).png",
    "answer": "ai",
    "fileName": "shot-03a_nano-pro (5).png"
  },
  {
    "id": "ai-31-c2hvdC0wM2IgKDQp",
    "src": "/ai/shot-03b%20(4).png",
    "answer": "ai",
    "fileName": "shot-03b (4).png"
  },
  {
    "id": "ai-32-c2hvdC0wNF9ncHQt",
    "src": "/ai/shot-04_gpt-image.png",
    "answer": "ai",
    "fileName": "shot-04_gpt-image.png"
  },
  {
    "id": "ai-33-c2hvdC0wNGIgKDEp",
    "src": "/ai/shot-04b%20(1).jpg",
    "answer": "ai",
    "fileName": "shot-04b (1).jpg"
  },
  {
    "id": "ai-34-c2hvdC0wNSAoNCku",
    "src": "/ai/shot-05%20(4).png",
    "answer": "ai",
    "fileName": "shot-05 (4).png"
  },
  {
    "id": "ai-35-c2hvdC0wNSAoNSku",
    "src": "/ai/shot-05%20(5).png",
    "answer": "ai",
    "fileName": "shot-05 (5).png"
  },
  {
    "id": "ai-36-c2hvdC0wNWFfbmFu",
    "src": "/ai/shot-05a_nano-pro%20(3).png",
    "answer": "ai",
    "fileName": "shot-05a_nano-pro (3).png"
  },
  {
    "id": "ai-37-c2hvdC0wNWFfbmFu",
    "src": "/ai/shot-05a_nano-pro%20(4).png",
    "answer": "ai",
    "fileName": "shot-05a_nano-pro (4).png"
  },
  {
    "id": "ai-38-c2hvdC0wNWJfbmFu",
    "src": "/ai/shot-05b_nano-pro%20(1).jpg",
    "answer": "ai",
    "fileName": "shot-05b_nano-pro (1).jpg"
  },
  {
    "id": "ai-39-c2hvdC0wNWJfbmFu",
    "src": "/ai/shot-05b_nano-pro%20(1).png",
    "answer": "ai",
    "fileName": "shot-05b_nano-pro (1).png"
  },
  {
    "id": "ai-40-c2hvdC0wNWIucG5n",
    "src": "/ai/shot-05b.png",
    "answer": "ai",
    "fileName": "shot-05b.png"
  },
  {
    "id": "ai-41-c2hvdC0wNyAoMyku",
    "src": "/ai/shot-07%20(3).png",
    "answer": "ai",
    "fileName": "shot-07 (3).png"
  },
  {
    "id": "ai-42-c2hvdC0wOCAoMyku",
    "src": "/ai/shot-08%20(3).png",
    "answer": "ai",
    "fileName": "shot-08 (3).png"
  },
  {
    "id": "ai-43-c2hvdC0wOF9uYW5v",
    "src": "/ai/shot-08_nano-pro.png",
    "answer": "ai",
    "fileName": "shot-08_nano-pro.png"
  },
  {
    "id": "ai-44-c2hvdC0wOSAoMiku",
    "src": "/ai/shot-09%20(2).png",
    "answer": "ai",
    "fileName": "shot-09 (2).png"
  },
  {
    "id": "ai-45-c2hvdC0xMV9uYW5v",
    "src": "/ai/shot-11_nano-pro_nano-pro%20(1).png",
    "answer": "ai",
    "fileName": "shot-11_nano-pro_nano-pro (1).png"
  },
  {
    "id": "ai-46-c2hvdC0xM19uYW5v",
    "src": "/ai/shot-13_nano-pro_nano-pro.png",
    "answer": "ai",
    "fileName": "shot-13_nano-pro_nano-pro.png"
  },
  {
    "id": "human-1-MDY3YzQ1OTEtZWI4",
    "src": "/human/067c4591-eb84-4269-b640-98eb99d40dc5.jpeg",
    "answer": "human",
    "fileName": "067c4591-eb84-4269-b640-98eb99d40dc5.jpeg"
  },
  {
    "id": "human-2-MzAyOWQwNWEtMjU4",
    "src": "/human/3029d05a-258f-49f3-bee0-d328b2bda808.jpeg",
    "answer": "human",
    "fileName": "3029d05a-258f-49f3-bee0-d328b2bda808.jpeg"
  },
  {
    "id": "human-3-M2I0OTZlMDktYzY5",
    "src": "/human/3b496e09-c698-46ff-b6a5-31ebc40084aa.jpeg",
    "answer": "human",
    "fileName": "3b496e09-c698-46ff-b6a5-31ebc40084aa.jpeg"
  },
  {
    "id": "human-4-NTUzNmU0ZmEtN2Ez",
    "src": "/human/5536e4fa-7a33-4ee5-98e8-4df6a763135c.jpeg",
    "answer": "human",
    "fileName": "5536e4fa-7a33-4ee5-98e8-4df6a763135c.jpeg"
  },
  {
    "id": "human-5-NzQ5Zjc1YzNlYjg5",
    "src": "/human/749f75c3eb89d388f77f207255b2e6e1.jpg",
    "answer": "human",
    "fileName": "749f75c3eb89d388f77f207255b2e6e1.jpg"
  },
  {
    "id": "human-6-OTNkNDg0NDgtYWFl",
    "src": "/human/93d48448-aaea-44ef-9cd1-13cb8d7cbbaa.jpeg",
    "answer": "human",
    "fileName": "93d48448-aaea-44ef-9cd1-13cb8d7cbbaa.jpeg"
  },
  {
    "id": "human-7-YjQ5NmI0NzQtNmIy",
    "src": "/human/b496b474-6b27-480d-8049-8e272a486a6a.jpeg",
    "answer": "human",
    "fileName": "b496b474-6b27-480d-8049-8e272a486a6a.jpeg"
  },
  {
    "id": "human-8-YmJhZjRjYTMtOWE2",
    "src": "/human/bbaf4ca3-9a64-4281-8075-7b96231599ea.jpeg",
    "answer": "human",
    "fileName": "bbaf4ca3-9a64-4281-8075-7b96231599ea.jpeg"
  },
  {
    "id": "human-9-YmNkNTM4MGMtNjNl",
    "src": "/human/bcd5380c-63e3-419e-b99b-b4caae5488d6.jpeg",
    "answer": "human",
    "fileName": "bcd5380c-63e3-419e-b99b-b4caae5488d6.jpeg"
  },
  {
    "id": "human-10-YzIwY2M2NDYtZjZj",
    "src": "/human/c20cc646-f6cc-4a65-bb49-f01a92ed777e.jpeg",
    "answer": "human",
    "fileName": "c20cc646-f6cc-4a65-bb49-f01a92ed777e.jpeg"
  },
  {
    "id": "human-11-ZWViYzg3OTMtZGVl",
    "src": "/human/eebc8793-dee5-4f6d-96e8-82cd9ab2b9a8.jpeg",
    "answer": "human",
    "fileName": "eebc8793-dee5-4f6d-96e8-82cd9ab2b9a8.jpeg"
  },
  {
    "id": "human-12-ZmY4ZDljZDgtNDAx",
    "src": "/human/ff8d9cd8-4014-4729-9663-c31d2ac2733a.jpeg",
    "answer": "human",
    "fileName": "ff8d9cd8-4014-4729-9663-c31d2ac2733a.jpeg"
  }
] as QuizImage[];
